### ISSUE TITLE
Java version and C++ version predict different probability values.

### ISSUE THREAD

**Issue by quanoc** [linkfluence/fastText4j#3]
Hello, when i use  fastText4j , the probability of java version and original C++ version prediction is different.

**Comment by quanoc** [comment]
What is the reason?

**Comment by JadeCopet** [comment]
Hi, 

It would help having additional information such as the model configuration (loss name, number of labels, with or without quantization etc) or an example to reproduce and identify what's going wrong. 

Thanks

**Comment by quantumcs** [comment]
charMatches method invoke by computeSubwords .  char in java has 2 byte, i think this wil  skip over some  chinese word , because char use unicode characters , include chinese word .  so i think `  protected boolean charMatches(char c) {
    return (c & 0xC0) == 0x80;
  }`   should be `  protected boolean charMatches(char c) {
    return c >=128 && c <=191;
  }`

**Comment by quantumcs** [comment]
charMatches method invoke by computeSubwords . char in java has 2 byte, i think this wil skip over some chinese word , because char use unicode characters , include chinese word . so i think 
```
protected boolean charMatches(char c) { 
    return (c & 0xC0) == 0x80; 
}
```
should be 
```
protected boolean charMatches(char c) { 
    return c >=128 && c <=191; 
}
```

**Comment by quantumcs** [comment]
charMatches method invoke by computeSubwords . char in java has 2 byte, i think this wil skip over some chinese word , because char use unicode characters in java , include chinese word . so i think
```java
protected boolean charMatches(char c) { 
    return (c & 0xC0) == 0x80; 
}
```
should be
```java
protected boolean charMatches(char c) { 
    return c >=128 && c <=191; 
}
```

**Comment by quantumcs** [comment]
Hi,
in my understanding.
```c
if ((word[i] & 0xC0) == 0x80) continue;
```
The purpose of this code  is to skip over the byte Cannot be a single word. 
Because  in the UTF-8 encoding rule, the byte with a beginning of 10 can not be a single word.
So they don't take the feature in computeSubwords.
but in java, this code:
```java
 protected boolean charMatches(char c) {
    return (c & 0xC0) == 0x80;
  }
```
will  skip over some word like chinese word. cause missing some word feature.

**Comment by quanoc** [comment]
Hi,
in my understanding.
```c
if ((word[i] & 0xC0) == 0x80) continue;
```
The purpose of this code is to skip over the byte Cannot be a single word.
Because in the UTF-8 encoding rule, the byte with a beginning of 10 can not be a single word.
this type of feature will not be taken in computeSubwords.
But in java, this code:
```java
protected boolean charMatches(char c) {
    return (c & 0xC0) == 0x80;
}
will skip over some word like chinese word. cause missing some word feature.

**Comment by skywalkerytx** [comment]
the different size of char in java/c++(2 bytes and 1 byte) made this

is this fixed?

**Comment by quanoc** [comment]
```java
protected boolean charMatches(char c) {
    return false;
}
```
That works. The probability difference of  Facebook`s c++ version and fastText4j prediction results is less than 0.05

**Comment by airlsyn** [comment]
java8 does not meet such thing
